services:
  postgres:
    image: postgres:latest
    container_name: club_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - ./club_db_postgres_data:/var/lib/postgresql/data:rw
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    ports:
      - "$PGADMIN_PORT:80"
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend: