"""destibation_for_certain_user

Revision ID: 201f1fb58358
Revises: 2b5e6b854e0c
Create Date: 2025-07-26 23:17:41.481962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '201f1fb58358'
down_revision: Union[str, Sequence[str], None] = '2b5e6b854e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('individual_for_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trainings', 'users', ['individual_for_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trainings', type_='foreignkey')
    op.drop_column('trainings', 'individual_for_id')
    # ### end Alembic commands ###
