"""user type

Revision ID: 2b5e6b854e0c
Revises: c49c63f29dd3
Create Date: 2025-07-26 19:55:54.820584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b5e6b854e0c'
down_revision: Union[str, Sequence[str], None] = 'c49c63f29dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE usertype AS ENUM ('COMPETITOR', 'NON_COMPETITOR', 'BEGINNER')"
    )
    op.add_column('users', sa.Column('user_type', sa.Enum('COMPETITOR', 'NON_COMPETITOR', 'BEGINNER', name='usertype'), nullable=False, server_default='NON_COMPETITOR'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    op.execute("DROP TYPE IF EXISTS usertype")
    # ### end Alembic commands ###
