"""add_user_interests_and_targeting_by_user_type

Revision ID: 829bee25abf5
Revises: da51b54f154c
Create Date: 2025-08-30 14:29:56.289004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '829bee25abf5'
down_revision: Union[str, Sequence[str], None] = 'da51b54f154c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

discipline_enum = postgresql.ENUM('MMA', 'STRIKING', 'BOXE_FEMININ', 'WRESTLING', 'BJJ', 'PHISICAL_PREPARATION', name='discipline', create_type=False)
usertype_enum = postgresql.ENUM('COMPETITOR', 'NON_COMPETITOR', 'BEGINNER', name='usertype', create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('discipline', discipline_enum, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'discipline')
    )
    op.create_index('interest_discipline_index', 'interests', ['discipline'], unique=False)
    op.create_index('interest_user_id_index', 'interests', ['user_id'], unique=False)
    op.add_column('trainings', sa.Column('target_user_type', usertype_enum, nullable=True, server_default=None))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainings', 'target_user_type')
    op.drop_index('interest_user_id_index', table_name='interests')
    op.drop_index('interest_discipline_index', table_name='interests')
    op.drop_table('interests')
    # ### end Alembic commands ###
