"""indexes_for_filtered_fields

Revision ID: da51b54f154c
Revises: e5bff5408fcd
Create Date: 2025-08-02 11:45:42.524037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da51b54f154c'
down_revision: Union[str, Sequence[str], None] = 'e5bff5408fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('available_trainings_training_id_index', 'available_trainings', ['training_id'], unique=False)
    op.create_index('available_trainings_user_id_index', 'available_trainings', ['user_id'], unique=False)
    op.create_index('training_target_auditory_index', 'trainings', ['target_auditory'], unique=False)
    op.create_index('training_target_gemder_index', 'trainings', ['target_gender'], unique=False)
    op.create_index('user_age_type_index', 'users', ['age_type'], unique=False)
    op.create_index('user_gender_index', 'users', ['gender'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_gender_index', table_name='users')
    op.drop_index('user_age_type_index', table_name='users')
    op.drop_index('training_target_gemder_index', table_name='trainings')
    op.drop_index('training_target_auditory_index', table_name='trainings')
    op.drop_index('available_trainings_user_id_index', table_name='available_trainings')
    op.drop_index('available_trainings_training_id_index', table_name='available_trainings')
    # ### end Alembic commands ###
