"""user_parameters_for_training_targeting

Revision ID: e5bff5408fcd
Revises: 201f1fb58358
Create Date: 2025-07-29 19:14:23.926981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5bff5408fcd'
down_revision: Union[str, Sequence[str], None] = '201f1fb58358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE auditory AS ENUM ('CHILDREN', 'ADULTS', 'SENIORS');")
    op.execute("CREATE TYPE gender AS ENUM ('M', 'W');")
    op.add_column('trainings', sa.Column('target_auditory', sa.Enum('CHILDREN', 'ADULTS', 'SENIORS', name='auditory'), nullable=True))
    op.add_column('trainings', sa.Column('target_gender', sa.Enum('M', 'W', name='gender'), nullable=True))
    op.add_column('users', sa.Column('age_type', sa.Enum('CHILDREN', 'ADULTS', 'SENIORS', name='auditory'), nullable=False, server_default='ADULTS'))
    op.add_column('users', sa.Column('gender', sa.Enum('M', 'W', name='gender'), nullable=True, server_default=None))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE auditory CASACDE;")
    op.execute("DROP TYPE gender CASACDE;")
    # ### end Alembic commands ###
