"""Rename field target_user_type to target_usertype

Revision ID: f668219954b1
Revises: 829bee25abf5
Create Date: 2025-09-02 17:14:40.269427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f668219954b1'
down_revision: Union[str, Sequence[str], None] = '829bee25abf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('target_usertype', sa.Enum('COMPETITOR', 'NON_COMPETITOR', 'BEGINNER', name='usertype'), nullable=True))
    op.drop_column('trainings', 'target_user_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('target_user_type', postgresql.ENUM('COMPETITOR', 'NON_COMPETITOR', 'BEGINNER', name='usertype'), autoincrement=False, nullable=True))
    op.drop_column('trainings', 'target_usertype')
    # ### end Alembic commands ###
